global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'config-service'
    static_configs:
      - targets: ['config-service:8001']
    metrics_path: '/metrics'

  - job_name: 'database-service'
    static_configs:
      - targets: ['database-service:8002']
    metrics_path: '/metrics'

  - job_name: 'exchange-service'
    static_configs:
      - targets: ['exchange-service:8003']
    metrics_path: '/metrics'

  - job_name: 'strategy-service'
    static_configs:
      - targets: ['strategy-service:8004']
    metrics_path: '/metrics'

  - job_name: 'orchestrator-service'
    static_configs:
      - targets: ['orchestrator-service:8005']
    metrics_path: '/metrics'

  - job_name: 'web-dashboard-service'
    static_configs:
      - targets: ['web-dashboard-service:8006']
    metrics_path: '/metrics' 